version: 2.1

jobs:
  build:
    docker:
      # use the same Docker image as your python app
      - image: python:3.7.3-stretch

    # working_directory: ~/repo

    steps:
      - checkout
      #Download the dependencies using the requirements.txt file
      #Cache the dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: |
            python3 -m venv myenv
            source myenv/bin/activate
            pip install --upgrade pip && pip install -r requirements.txt
            #install hadolint for Dockerfile
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./myenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      #run make lint. lint must score 10.00/10.00 
      - run:
          name: Run Lint
          command: |
            source myenv/bin/activate
            make lint

workflows:
  halima-workflow:
    jobs:
      - build
